feat: update
jpshackelford/jpshackelford-blog pull request #5
Opened 2023-12-08 20:21 UTC by usphantomlancer

2023-12-08 21:03 UTC, jpshackelford requested changes
Please see comments on jps.css.

2023-12-08 23:49 UTC, usphantomlancer commented on static/css/jps.css
> +article:not([data-theme=dark]) {
Okay. Got it.

2023-12-11 13:48 UTC, usphantomlancer commented on static/css/jps.css
> +article:not([data-theme=dark]) {
Hi, John. I have pushed the updates. Please check.

2023-12-11 15:08 UTC, jpshackelford commented on static/css/jps.css
> +article:not([data-theme=dark]) {
I've verified. Thanks very much!

2023-12-11 16:25 UTC, merged